wallpaper:   "{{ home_dir }}/Pictures/wallpaper/bokeh.jpg"
colors:
  name:         "bokeh"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#be7c45"
    bold:       "#f09c57"
  green: 
    normal:     "#bdad67"
    bold:       "#efda82"
  yellow: 
    normal:     "#9cc183"
    bold:       "#c4f3a4"
  blue: 
    normal:     "#8769a9"
    bold:       "#ae88db"
  magenta: 
    normal:     "#a95b88"
    bold:       "#db75b0"
  cyan: 
    normal:     "#ae3f45"
    bold:       "#e05158" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
