wallpaper:   "{{ home_dir }}/Pictures/wallpaper/bright-sky.jpg"
bar_bg_alpha:   "99"
colors:
  name:         "bright-sky"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#bec6c2"
    bold:       "#edf8f2"
  green: 
    normal:     "#9ec3c7"
    bold:       "#c5f3f9"
  yellow: 
    normal:     "#81bec8"
    bold:       "#a1edfa"
  blue: 
    normal:     "#64b8c8"
    bold:       "#7de5fa"
  magenta: 
    normal:     "#48b3c7"
    bold:       "#5adff9"
  cyan: 
    normal:     "#2aa1c8"
    bold:       "#34c9fa" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
