wallpaper:   "{{ home_dir }}/Pictures/wallpaper/cave.jpg"
colors:
  name:         "cave"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#bfc787"
    bold:       "#eef9a8"
  green: 
    normal:     "#98ba7b"
    bold:       "#c0ec9c"
  yellow: 
    normal:     "#72ab79"
    bold:       "#93dd9c"
  blue: 
    normal:     "#59aa8e"
    bold:       "#73dcb7"
  magenta: 
    normal:     "#5aa2a6"
    bold:       "#75d2d8"
  cyan: 
    normal:     "#9d79a0"
    bold:       "#ce9ed2" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
