wallpaper:   "{{ home_dir }}/Pictures/wallpaper/eva-pilots-colorful.jpg"
colors:
  name:         "eva-pilots-colorful"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#c72e1f"
    bold:       "#f93926"
  green: 
    normal:     "#c78f6b"
    bold:       "#f9b285"
  yellow: 
    normal:     "#c87a0f"
    bold:       "#fa9812"
  blue: 
    normal:     "#bec1c0"
    bold:       "#eff3f1"
  magenta: 
    normal:     "#99b7c6"
    bold:       "#bfe5f8"
  cyan: 
    normal:     "#4787be"
    bold:       "#59aaf0" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
