wallpaper:   "{{ home_dir }}/Pictures/wallpaper/geometry.jpg"
colors:
  name:         "geometry"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#b4352b"
    bold:       "#e64336"
  green: 
    normal:     "#a96659"
    bold:       "#db8473"
  yellow: 
    normal:     "#c27627"
    bold:       "#f49431"
  blue: 
    normal:     "#acb14d"
    bold:       "#dce362"
  magenta: 
    normal:     "#5cab5d"
    bold:       "#76dd78"
  cyan: 
    normal:     "#22a385"
    bold:       "#2cd5ad" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
