wallpaper:   "{{ home_dir }}/Pictures/wallpaper/gits-bg.jpg"
colors:
  name:         "gits-bg"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#bdb1ac"
    bold:       "#efdfd9"
  green: 
    normal:     "#626caa"
    bold:       "#7e8bdc"
  yellow: 
    normal:     "#888ca9"
    bold:       "#b0b5db"
  blue: 
    normal:     "#5046aa"
    bold:       "#675adc"
  magenta: 
    normal:     "#965ca6"
    bold:       "#c377d8"
  cyan: 
    normal:     "#b3787b"
    bold:       "#e5999d" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
