wallpaper:   "{{ home_dir }}/Pictures/wallpaper/pink-flowers.jpg"
colors:
  name:         "pink-flowers"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#c7b5b4"
    bold:       "#f9e2e1"
  green: 
    normal:     "#c3bd8a"
    bold:       "#f5edad"
  yellow: 
    normal:     "#bab763"
    bold:       "#ece87d"
  blue: 
    normal:     "#b7b7c7"
    bold:       "#e4e4f9"
  magenta: 
    normal:     "#c22875"
    bold:       "#f43293"
  cyan: 
    normal:     "#c5768d"
    bold:       "#f793b0" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
