wallpaper:   "{{ home_dir }}/Pictures/wallpaper/samoyed-mossy.jpg"
colors:
  name:         "samoyed-mossy"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#aa4a3c"
    bold:       "#dc5f4d"
  green: 
    normal:     "#9ba739"
    bold:       "#c9d94a"
  yellow: 
    normal:     "#80aa28"
    bold:       "#a5dc33"
  blue: 
    normal:     "#9da98d"
    bold:       "#cbdbb6"
  magenta: 
    normal:     "#bdc5b8"
    bold:       "#ecf7e6"
  cyan: 
    normal:     "#5eaa33"
    bold:       "#79dc42" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
