wallpaper:   "{{ home_dir }}/Pictures/wallpaper/starry-forest.jpg"
colors:
  name:         "starry-forest"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#6492c5"
    bold:       "#7db7f7"
  green: 
    normal:     "#8aa5c3"
    bold:       "#adcff5"
  yellow: 
    normal:     "#567dac"
    bold:       "#6fa1de"
  blue: 
    normal:     "#4774ab"
    bold:       "#5b95dd"
  magenta: 
    normal:     "#3a6caa"
    bold:       "#4b8bdc"
  cyan: 
    normal:     "#7087a9"
    bold:       "#91aedb" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
