#!/bin/bash

# Provides a colorized definition of the given word

# Args:
#   $1: The word to define.
#   $2: The dictionary to use. (Optional)

# Use an optional second parameter as the dictionary name
if [[ -z "$2" ]]; then
	database=wn
else
	database=$2
fi

dict -d $database $1 | colorit
