#!/bin/bash

# Gets new email with offlineimap using GNOME Keyring for authentication.
# This script is good for running via cron.

source $HOME/.Xdbus
read -r pid < $HOME/.offlineimap/pid

if ps $pid &>/dev/null; then
	echo "offlineimap ($pid): another instance running." >&2
	kill -9 $pid
fi

/usr/bin/offlineimap -o -u quiet &
