#!/bin/bash

# Starts Bitlbee, and opens irssi with the nicklist script in tmux

if [ -n "$TMUX" ]; then
	# If we're currently in a tmux session, don't create a new one
	session_existed=true
	session_info=""
else
	session_existed=false
	# Session parameter for tmux commands
	session_info="-t chat"

	# Create a new tmux session called "chat"
	tmux new-session -d -s chat
fi

# Create the nicklist pane
tmux split-window $session_info -h -l 20

# irssi && tmux kill-pane -t1 && exit closes the nicklist pane and exits the tmux window
# The rest of these commands configure the nicklist and move focus to irssi's pane
tmux send-keys $session_info "tmux send-keys -t0 \"irssi && tmux kill-pane -t1 && exit\" C-m; \
	tmux send-keys -t0 \"/set nicklist_height \$(stty size | cut -f1 -d' ' -)\" C-m; \
	tmux send-keys -t0 \"/set nicklist_width \$(stty size | cut -f2 -d' ' -)\" C-m; \
	tmux send-keys -t0 \"/nicklist fifo\" C-m; \
	tmux send-keys \"cat ~/.irssi/nicklistfifo\" C-m; \
	tmux select-pane -t0" C-m

# If we created a new session, attach it
if ! $session_existed; then
	tmux attach-session $session_info
fi
