# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# colors
red='\e[0;31m'
magenta='\e[0;35m'
bright_red='\e[0;91m'
yellow='\e[0;33m'
green='\e[0;32m'
blue='\e[0;34m'
bright_blue='\e[0;94m'
normal='\e[0m'

# prompt
PS1="\$(if [[ \$? == 0 ]]; then echo '\[${green}\]'; else echo '\[${yellow}\]'; fi)⚘ \[${red}\]\W\[${normal}\] "

# git prompt
if [ -f ~/.git-prompt.sh ]; then
  source ~/.git-prompt.sh
  export PS1="$PS1\[${blue}\]\$(__git_ps1 \"(%s)\")\[${normal}\] "
fi

# travis ci
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

# private bashrc
[ -f ~/.private-bashrc ] && source ~/.private-bashrc

# use vim as default editor
EDITOR=vim

# keep repeated commands in history once
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend cmdhist

# add ruby gems to path
if which ruby >/dev/null 2>&1 && which gem >/dev/null; then
  export PATH="$PATH:$(ruby -rubygems -e 'puts Gem.user_dir')/bin"
fi

# add user executables to path (from pip --user)
PATH="$PATH:$HOME/.local/bin"

# thefuck
if command -v thefuck >/dev/null 2>&1; then
  eval "$(thefuck --alias f)"
fi

# git aliases
alias ga="git add"
alias gs="git status"
alias gc="git commit -m"
alias gp="git push -u origin \$(git rev-parse --abbrev-ref HEAD)"
alias gmd="git checkout develop && git pull && git checkout - && git merge develop"
alias mb="git merge-base HEAD"

# system aliases
alias brc="$EDITOR ~/.bashrc && source ~/.bashrc"
alias grep="grep --color=auto"
alias sizeof="du -Lhs"

if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS aliases
  alias ls="ls -G"

  # add latex to path on macOS
  export PATH=/usr/local/bin:$PATH
  export PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin
else
  # linux aliases
  alias ls="ls --color=auto"
fi

# arch linux aliases
if command -v yaourt >/dev/null 2>&1; then
  alias update="yaourt -Syu --aur"
  alias removeorphans="yaourt -Rns \$(yaourt -Qqtd)"
  alias clearpkgcache="yaourt -Scc"
fi

# docker aliases
if command -v docker >/dev/null 2>&1; then
  alias dclean='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'
fi

# gcalcli aliases
if command -v gcalcli >/dev/null 2>&1; then
  alias gcald="gcalcli --military --detail_location --detail_length --detail_reminders --detail_description agenda 12am 11:59pm"
  alias gcalw="gcalcli --military calw"
  alias gcalm="gcalcli --military calm"
fi

# gcalcli aliases
if command -v dict >/dev/null 2>&1; then
  # Provides a colorized definition of the given word
  #   $1: The word to define.
  #   $2: The dictionary to use. (Optional)
  define() {
    # Use an optional second parameter as the dictionary name
    if [[ -z "$2" ]]; then
      database=gcide
    else
      database=$2
    fi

    dict -d $database $1 | colorit | less -r
  }

  # Provides the English for the given Swedish
  #   $1: The word to translate
  swen() {
    define $1 fd-swe-eng
  }

  # Provides the Swedish for the given English
  #   $1: The word to translate
  ensw() {
    define $1 fd-eng-swe
  }

  # Provides a colorized thesaurus entry for the given word
  #   $1: The word to look up
  thes() {
    define $1 moby-thesaurus
  }
fi
