if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

# Returns true if the given command is available
hascmd() { command -v $1 >/dev/null 2>&1; }

if hascmd brew && [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export PATH="$HOME/.cargo/bin:$PATH"
