#! /bin/sh

bspc config border_width {{ border_size }}
bspc config window_gap   {{ window_gap_size }}

bspc config split_ratio           {{ window_split_ratio }}
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Clear out old rules
for x in {1..100}; do bspc rule -r head; done

bspc rule -a URxvt:scratchpad state=floating sticky=on center=on
