#! /bin/sh

bspc config border_width {{ border_size }}
bspc config window_gap   {{ window_gap_size }}

bspc config split_ratio           {{ window_split_ratio }}
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Clear out old rules
for x in {1..100}; do bspc rule -r head; done

bspc rule -a URxvt:scratchpad state=floating sticky=on center=on

source "$HOME/.cache/wal/colors.sh"

# Software
compton &
dropbox &
gcalert &
dunst \
  -lb "${color0:=#F0F0F0}" \
  -nb "$color0" \
  -cb "$color0" \
  -lf "${color8:=#000000}" \
  -bf "$color8" \
  -cf "$color8" \
  -nf "$color8" \
  > /dev/null 2>&1 &

# Start sxhkd if it is not running
if ! pgrep sxhkd > /dev/null; then
	sxhkd &
fi

# Start xss-lock if it is not running
if hash katie_lock 2>/dev/null; then
	if ! pgrep xss-lock > /dev/null; then
		xss-lock -n katie_lock katie_lock &
	fi
fi

# Start the urxvt daemon if it is not running
if ! pgrep "urxvtd" > /dev/null; then
	urxvtd --quiet --opendisplay --fork
fi

# Panel
polybar default &
