wallpapers: "~/Pictures/wallpaper/blue-gradient.jpg"

name:           "blue-gradient"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#b2c8a4"
    bold:       "#defacd"
  green:
    normal:     "#92c7b2"
    bold:       "#b6f9de"
  yellow:
    normal:     "#73c5bf"
    bold:       "#90f7ef"
  blue:
    normal:     "#57b1b5"
    bold:       "#6fe1e7"
  magenta:
    normal:     "#3d9fad"
    bold:       "#4eccdf"
  cyan:
    normal:     "#1f8faa"
    bold:       "#28b9dc"
