wallpapers: "~/Pictures/wallpaper/bright-flowers.jpg"

name:           "bright-flowers"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#bcc740"
    bold:       "#ebf950"
  green:
    normal:     "#b5c75f"
    bold:       "#e2f976"
  yellow:
    normal:     "#afc786"
    bold:       "#daf9a7"
  blue:
    normal:     "#b3c8b1"
    bold:       "#dffadd"
  magenta:
    normal:     "#66b890"
    bold:       "#81eab7"
  cyan:
    normal:     "#9cc7bc"
    bold:       "#c3f9eb"
