wallpapers: "~/Pictures/wallpaper/brunette.png"

name:           "brunette"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#c28c78"
    bold:       "#f4b096"
  green:
    normal:     "#c5b0a6"
    bold:       "#f7dcd0"
  yellow:
    normal:     "#c7a18b"
    bold:       "#f9c9ad"
  blue:
    normal:     "#8495a9"
    bold:       "#abc1db"
  magenta:
    normal:     "#a86795"
    bold:       "#da85c1"
  cyan:
    normal:     "#aa636a"
    bold:       "#dc8089"
