wallpapers: "~/Pictures/wallpaper/cat-licking.jpg"

name:           "cat-licking"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#ab5f39"
    bold:       "#dd7a49"
  green:
    normal:     "#b0724f"
    bold:       "#e29265"
  yellow:
    normal:     "#aa8c79"
    bold:       "#dcb59c"
  blue:
    normal:     "#c3885a"
    bold:       "#f5aa71"
  magenta:
    normal:     "#c7a17d"
    bold:       "#f9c99c"
  cyan:
    normal:     "#c8b49d"
    bold:       "#fae1c4"
