wallpapers: "~/Pictures/wallpaper/drawn.jpg"

name:           "drawn"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#c4b49b"
    bold:       "#f6e1c2"
  green:
    normal:     "#c0c4af"
    bold:       "#f0f6db"
  yellow:
    normal:     "#9fad9c"
    bold:       "#ccdfc9"
  blue:
    normal:     "#9ec4c0"
    bold:       "#c6f6f0"
  magenta:
    normal:     "#75aeb6"
    bold:       "#95dde8"
  cyan:
    normal:     "#4f8cad"
    bold:       "#65b4df"
