wallpapers: "~/Pictures/wallpaper/geometry.jpg"

name:           "geometry"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#b5332b"
    bold:       "#e74136"
  green:
    normal:     "#a9655a"
    bold:       "#db8274"
  yellow:
    normal:     "#c27527"
    bold:       "#f49331"
  blue:
    normal:     "#acb14e"
    bold:       "#dce364"
  magenta:
    normal:     "#5bab5d"
    bold:       "#75dd78"
  cyan:
    normal:     "#23a18a"
    bold:       "#2dd3b4"
