wallpapers: "~/Pictures/wallpaper/gits-bg.jpg"

name:           "gits-bg"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#bdb0ac"
    bold:       "#efded9"
  green:
    normal:     "#888da9"
    bold:       "#b0b6db"
  yellow:
    normal:     "#626caa"
    bold:       "#7e8bdc"
  blue:
    normal:     "#5046aa"
    bold:       "#675adc"
  magenta:
    normal:     "#965ca5"
    bold:       "#c377d7"
  cyan:
    normal:     "#b3787b"
    bold:       "#e5999d"
