wallpapers: "~/Pictures/wallpaper/green_light.jpg"

name:           "green_light"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#b9c69f"
    bold:       "#e7f8c7"
  green:
    normal:     "#9abb98"
    bold:       "#c3edc0"
  yellow:
    normal:     "#80ab90"
    bold:       "#a5ddba"
  blue:
    normal:     "#72aa97"
    bold:       "#93dcc3"
  magenta:
    normal:     "#64a9a2"
    bold:       "#81dbd1"
  cyan:
    normal:     "#56a1a8"
    bold:       "#6fd0da"
