wallpapers: "~/Pictures/wallpaper/light-gradient.jpg"

name:           "light-gradient"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#a0b4b6"
    bold:       "#cbe5e8"
  green:
    normal:     "#8aa5aa"
    bold:       "#b2d5dc"
  yellow:
    normal:     "#729ca9"
    bold:       "#93cadb"
  blue:
    normal:     "#b8c1c5"
    bold:       "#e6f1f7"
  magenta:
    normal:     "#9f93a8"
    bold:       "#cebeda"
  cyan:
    normal:     "#bcaab6"
    bold:       "#eed7e6"
