wallpapers: "~/Pictures/wallpaper/light-blue-gradient.jpg"

name:           "light-blue-gradient"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#6dbac7"
    bold:       "#88e8f9"
  green:
    normal:     "#58b1c0"
    bold:       "#6edff2"
  yellow:
    normal:     "#82bdc8"
    bold:       "#a2ecfa"
  blue:
    normal:     "#96c0c8"
    bold:       "#bbf0fa"
  magenta:
    normal:     "#aac3c8"
    bold:       "#d4f3fa"
  cyan:
    normal:     "#bec6c8"
    bold:       "#edf7fa"
