wallpaper:   "{{ home_dir }}/Pictures/wallpaper/puphypa.jpg"
bar_bg_alpha:   "99"
colors:
  name:         "puphypa"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#97adb8"
    bold:       "#c0dcea"
  green: 
    normal:     "#8b6fac"
    bold:       "#b38fde"
  yellow: 
    normal:     "#bfb6c2"
    bold:       "#f0e4f4"
  blue: 
    normal:     "#c28fc3"
    bold:       "#f3b3f5"
  magenta: 
    normal:     "#c372ac"
    bold:       "#f58fd8"
  cyan: 
    normal:     "#b35584"
    bold:       "#e56ca8" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
