wallpapers: "~/Pictures/wallpaper/purple_light.jpg"

name:           "purple_light"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#78acc8"
    bold:       "#96d7fa"
  green:
    normal:     "#a1aec8"
    bold:       "#c9d9fa"
  yellow:
    normal:     "#758cc8"
    bold:       "#92affa"
  blue:
    normal:     "#8e95c8"
    bold:       "#b1bafa"
  magenta:
    normal:     "#7b5ec7"
    bold:       "#9975f9"
  cyan:
    normal:     "#9379c8"
    bold:       "#b797fa"
