wallpaper:   "{{ home_dir }}/Pictures/wallpaper/rainbow.jpg"
colors:
  name:         "rainbow"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#c7905f"
    bold:       "#f9b476"
  green: 
    normal:     "#bbb787"
    bold:       "#ede7ab"
  yellow: 
    normal:     "#80bd9b"
    bold:       "#a1efc4"
  blue: 
    normal:     "#47abab"
    bold:       "#5bdddd"
  magenta: 
    normal:     "#9487a3"
    bold:       "#c1b0d5"
  cyan: 
    normal:     "#bd5e75"
    bold:       "#ef7693" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
