wallpaper:   "{{ home_dir }}/Pictures/wallpaper/rei-colorful.jpg"
colors:
  name:         "rei-colorful"
  background:   "#0e0e0e"
  foreground:   "#ffffff"
  primary:      "red"
  secondary:    "green"
  black:
    normal:     "#161d20"
    bold:       "#6f6d80"
  red:
    normal:     "#a5a4a2"
    bold:       "#d7d5d3"
  green: 
    normal:     "#91b165"
    bold:       "#b9e381"
  yellow: 
    normal:     "#649fa8"
    bold:       "#81ceda"
  blue: 
    normal:     "#179bbb"
    bold:       "#1dc4ed"
  magenta: 
    normal:     "#b63a60"
    bold:       "#e8497a"
  cyan: 
    normal:     "#c4c4c4"
    bold:       "#f6f6f6" 
  white: 
    normal:     "#d7bdad"
    bold:       "#a685c8"
