wallpapers: "~/Pictures/wallpaper/soft-pink.jpg"

name:           "soft-pink"
colors:
  primary:      "red"
  secondary:    "blue"
  red:
    normal:     "#82b5c4"
    bold:       "#a3e3f6"
  green:
    normal:     "#a1b9c7"
    bold:       "#c9e7f9"
  yellow:
    normal:     "#bebcc7"
    bold:       "#edebf9"
  blue:
    normal:     "#aa96b8"
    bold:       "#d8beea"
  magenta:
    normal:     "#c6b1bf"
    bold:       "#f8ddef"
  cyan:
    normal:     "#c6a4b2"
    bold:       "#f8cdde"
