colors:
  name:         "thayer"
  primary:      "red"
  secondary:    "green"
  background:   "#191919"
  foreground:   "#f0eac8"
  black:
    normal:     "#555544"
    bold:       "#545466"
  red:
    normal:     "#aa5654"
    bold:       "#f92672"
  green:
    normal:     "#BEED5F"
    bold:       "#f9ecbe"
  yellow:
    normal:     "#E6DB74"
    bold:       "#f7d287"
  blue:
    normal:     "#66D9EF"
    bold:       "#dcc4b5"
  magenta:
    normal:     "#9E6FFE"
    bold:       "#dca99f"
  cyan:
    normal:     "#A3BABF"
    bold:       "#f9f6d2"
  white:
    normal:     "#F8F8F2"
    bold:       "#eaeaea"
