# System
xft_dpi: 144

# GTK
gtk_theme: "Arc-Dark"
gtk_icon_theme: "Arc"
gtk_font_size: 10

# Fonts
font: "M+ 1p"
term_fonts:
  - "Dank Mono"
use_bold: false
pixelsize: 18
term_letterspace: 0

# WM
window_split_ratio: 0.5
window_gap_size: 15
border_size: 5

# dmenu
dmenu_flags: '-i -f -fn "{{ font }}:pixelsize={{ pixelsize }}" -b'

# bar
bar_height: 32
bar_underline: 3
bar_fonts:
  - "M+ 1p-14;3"

# dunst
dunst_offset: 15
dunst_geometry: "460x8-{{ dunst_offset }}+{{ bar_height + dunst_offset }}"
dunst_transparency: 15
dunst_border_size: 0
dunst_padding: 20
dunst_font: "M+ 1p-8"
dunst_font_size: 10
