#! /bin/sh

bspc config border_width 5
bspc config window_gap   15

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Clear out old rules
for x in {1..100}; do bspc rule -r head; done

bspc rule -a URxvt:scratchpad state=floating sticky=on center=on
