#!/usr/bin/env sh

# Source colors from wal if able
[ -f "$HOME/.cache/wal/colors.sh" ] && . "$HOME/.cache/wal/colors.sh"

bspc config border_width 10
bspc config window_gap   30

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier      mod1
bspc config normal_border_color   "$background" # Unfocused window
bspc config active_border_color   "$color5" # Focused window on unfocused monitor
bspc config focused_border_color  "$color3" # Focused window on focused monitor
bspc config presel_feedback_color "$color3"

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Clear out old rules
for x in {1..100}; do bspc rule -r head; done

bspc rule -a XTerm:scratchpad state=floating sticky=on center=on
bspc rule -a Rofi state=floating sticky=on center=on
