#! /bin/sh

bspc config border_width {{ border_size }}
bspc config window_gap   {{ window_gap_size }}

bspc config focused_border_color "{{ n_primary }}"
bspc config normal_border_color  "{{ fgc }}"
bspc config focused_sticky_border_color "{{ n_secondary }}"
bspc config normal_sticky_border_color  "{{ fgc }}"

bspc config split_ratio           {{ window_split_ratio }}
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true

bspc monitor -d 一 二 三 四 五 六 七 八 九 十


# Clear out old rules
for x in {1..100}; do bspc rule -r head; done

bspc rule -a Skype state=floating
bspc rule -a Telegram state=floating
bspc rule -a telegram-desktop state=floating
bspc rule -a Polly state=floating
bspc rule -a Ccgo state=pseudo_tiled
bspc rule -a URxvt:scratchpad state=floating center=on

# Software
compton &
dropbox &
gcalert &
dunst > /dev/null 2>&1 &

# Start sxhkd if it is not running
if ! pgrep sxhkd > /dev/null; then
	sxhkd &
fi

#$HOME/.fehbg $HOME/Pictures/wallpaper 5m fill &
. $HOME/.fehbg &

# Start the urxvt daemon if it is not running
if ! pgrep "urxvtd" > /dev/null; then
	urxvtd --quiet --opendisplay --fork
fi

# Panel
bspc config top_padding {{ bar_height }}
. $HOME/.config/lemonbar/lemonbar &
