#!/bin/sh

# $1: The wallpaper directory (Default ~/Pictures/wallpaper)
# $2: The time between changing wallpapers (Default 15m)
# $3: The wallpaper display style (Default fill)
#     One of center, fill, max, scale, or tile.

wallpapers=${1:-~/Pictures/wallpaper}
change_after=${2:-15m}
style=${3:-fill}

while true; do
	find $wallpapers -type f \( -name '*.jpg' -o -name '*.png' \) -print0 |
		shuf -n1 -z | xargs -0 feh --no-fehbg "--bg-$style"
	sleep $change_after
done
