#!/usr/bin/env sh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIR="$HOME/.config"
export PATH="$PATH:$HOME/.local/bin"
export GDK_DPI_SCALE=0.35
export GDK_SCALE=2

# use the menu key as the compose key
setxkbmap -option compose:menu

# start my desktop if the script is available
command -v bonjour >/dev/null 2>&1 && bonjour
