#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export GDK_DPI_SCALE=0.35
export GDK_SCALE=2

# Use the menu key as the compose key
setxkbmap -option compose:menu

# Apply previous wal theme if installed
if command -v wal >/dev/null 2>&1; then
  wal -R
fi
