#!/bin/bash

# Use the menu key as the compose key
setxkbmap -option compose:menu

# ----- For using gnome-keyring

# Start a dbus session
#source /etc/X11/xinit/xinitrc.d/30-dbus.sh

# Start GNOME Keyring
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh

~/.fehbg ~/Pictures/wallpaper 5m fill &

compton -b
xmonad --replace &
