#!/bin/bash

# For using 32-bit GTK themes with Skype
export GTK2_RC_FILES="/etc/gtk-2.0/gtkrc:$HOME/.gtkrc-2.0"

# Use the menu key as the compose key
setxkbmap -option compose:menu

# ----- For using gnome-keyring

# Start a dbus session
source /etc/X11/xinit/xinitrc.d/30-dbus

# Start GNOME Keyring
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh
