#!/usr/bin/env bash
# Runs colorz2 on an image file to get 6 colors, then stuffs those colors
# through wzk.

# http://stackoverflow.com/a/13221491
exists() {
  if [ "$2" != in ]; then
    echo "Incorrect usage."
    echo "Correct usage: exists {key} in {array}"
    return
  fi
  eval '[ ${'$3'[$1]+muahaha} ]'
}

usage() {
  echo "USAGE: autowzk [image file / URL] (primary color) (secondary color)"
  echo "If image URL provided, image will be saved at \"~/.autowzk\"."
  echo "Available colors: 2 (red),  3 (green),   4 (yellow),"
  echo "                  5 (blue), 6 (magenta), 7 (cyan)"
  echo "Defaults: primary=2, secondary=3"
  exit 1
}

SRC=~/.autowzk
BG="#0e0e0e"
FG="#ffffff"
B_n="#161d20"
B_b="#6f6d80"
W_n="#d7bdad"
W_b="#a685c8"

declare -A COLORS
COLORS=(
  [2]=red
  [3]=green
  [4]=yellow
  [5]=blue
  [6]=magenta
  [7]=cyan
)

read -r -d '' TEMPLATE << EOM
wallpaper:   "%s"
colors:
  name:         "%s"
  background:   "%s"
  foreground:   "%s"
  primary:      "%s"
  secondary:    "%s"
  black:
    normal:     "%s"
    bold:       "%s"
  red:
    normal:     "%s"
    bold:       "%s"
  green: 
    normal:     "%s"
    bold:       "%s"
  yellow: 
    normal:     "%s"
    bold:       "%s"
  blue: 
    normal:     "%s"
    bold:       "%s"
  magenta: 
    normal:     "%s"
    bold:       "%s"
  cyan: 
    normal:     "%s"
    bold:       "%s" 
  white: 
    normal:     "%s"
    bold:       "%s" 
EOM

# Sanity checks, getting args
[ "$#" -lt 1 ] || [ "$#" -gt 3 ] && usage

if [ ! -f "$1" ]; then
  [[ "$1" != http* ]] && usage

  curl "$1" -o "$SRC" 2>/dev/null || (echo "URL invalid." && exit 1)
else
  SRC="$1"
fi

NAME=$(basename $SRC)
NAME=${NAME%.*}

if [ -z "$2" ]; then
  # Default
  primary="2"
else
  exists "$2" in COLORS 2>/dev/null && primary="$2" || usage
fi

if [ -z "$3" ]; then
  # Default
  secondary="3"
else
  exists "$3" in COLORS 2>/dev/null && secondary="$3" || usage
fi

# Starting...
echo "Using primary=$primary, secondary=$secondary..."
echo

colors="$(previewcolors --no-preview -n 6 "$SRC")"
[ "${PIPESTATUS[0]}" -ne 0 ] && exit 1

primaries="$(echo "$colors" | sed -n "$((primary - 1))p")"

FULL_SRC=$(readlink -f "$SRC")
VAR_SRC=${FULL_SRC/$HOME/"{{ home_dir }}"}

yaml="$(echo \
  "$NAME" "$BG" "$FG" \
  "${COLORS[$primary]}" "${COLORS[$secondary]}" \
  "$B_n" "$B_b" \
  "$colors" \
  "$W_n" "$W_b" |\
  xargs printf "$TEMPLATE" "$VAR_SRC")"

#echo "Generated YAML:"
echo "$yaml" > "$HOME/.config/whizkers/variable_sets/$NAME.yaml"
#echo
