#!/usr/bin/env bash
# Opens a tmux session with a window for each mutt inbox.
#
# Author:  Kate Hart (https://github.com/codehearts)
# Depends: tmux

# Gmail (1)
if [ -n "$TMUX" ]; then
	# If we're currently in a tmux session, don't create a new one
	session_existed=true
	session_info=""
	
	# Just rename the current window
	tmux rename-window Gmail
else
	session_existed=false
	# Session parameter for tmux commands
	session_info="-t email"

	# Create a new session called "email"
	tmux new-session -d -s email -n Gmail
fi
tmux send-keys $session_info "neomutt -f ~/Mail/Gmail/Inbox" C-m

# Kate Hart (2)
tmux new-window $session_info -n KateHart
tmux send-keys $session_info "neomutt -f ~/Mail/KateHart/Inbox" C-m

# Set the window history order (the last line is the current window)
tmux select-window -t Gmail
tmux select-window -t KateHart

# If we created a new session, attach it
if ! $session_existed; then
	tmux attach-session $session_info
fi
