#!/usr/bin/env bash
# Reloads ~/.Xresources and my running desktop software.
#
# References: use-color from http://superuser.com/a/921802
# Author:  Kate Hart (https://github.com/codehearts)
# Depends: xrdb

xrdb ~/.Xresources

use-color() {
  tr -d ' \t' | sed -n '
  s/.*\.font:/\x1b]710;/p
  s/.*\.boldFont:/\x1b]711;/p
  s/.*\.italicFont:/\x1b]712;/p
  s/.*\.boldItalicFont:/\x1b]713;/p
  s/.*\.background:/\x1b]11;/p
  s/.*\.foreground:/\x1b]10;/p
  s/.*\.borderColor:/\x1b]708;/p
  s/.*\.color\([0-9][^:]*\):/\x1b]4;\1;/p
  ' | tr \\n \\a
}

for pts in /dev/pts/*; do
	(echo -n "$(use-color < ~/.Xresources)" > $pts) 2>/dev/null
done

pkill lemonbar
pkill compton
pkill dropbox
pkill gcalert
pkill dunst
pkill bspwmrc

exec ${HOME}/.config/bspwm/bspwmrc
