#!/usr/bin/env bash
# Reloads my running desktop software and applies colorschemes.
#
# Author: Kate Hart (https://github.com/codehearts)

is_installed() {
  command -v "$1" >/dev/null 2>&1
}

# Reload the bspwmrc if available
[ -f "$HOME/.config/bspwm/bspwmrc" ] && source "$HOME/.config/bspwm/bspwmrc"

# Apply Xresources
is_installed xrdb && xrdb "$HOME/.Xresources"

# Apply previous wal theme if wal is installed
is_installed wal && wal -R

# Source colors for the current theme
source "$HOME/.cache/wal/colors.sh"

# Start picom if it's not already
if ! pgrep 'picom' > /dev/null; then
  picom &
fi

# Start the urxvt daemon if it's not running
if is_installed urxvtd && ! pgrep 'urxvtd' > /dev/null; then
	urxvtd --quiet --opendisplay --fork
fi

# Start or reload sxhkd
if pgrep 'sxhkd' > /dev/null; then
  pkill -USR1 -x sxhkd
elif is_installed sxhkd; then
	sxhkd &
fi

# Start dropbox if it's not running
if is_installed dropbox && ! pgrep dropbox > /dev/null; then
  dropbox &
fi

# Lock the machine on sleep or after 10m
if is_installed xsecurelock && ! pgrep xss-lock > /dev/null; then
  xset s 600

  XSECURELOCK_SHOW_USERNAME=0 \
  XSECURELOCK_SHOW_HOSTNAME=0 \
  XSECURELOCK_SHOW_DATETIME=0 \
  XSECURELOCK_PASSWORD_PROMPT=hidden \
  XSECURELOCK_SAVER=saver_mpv \
  XSECURELOCK_LIST_VIDEOS_COMMAND='feh --zoom=fill -Ff ~/.cache/wal/wal' \
  XSECURELOCK_NO_COMPOSITE=1 \
    xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
fi

# Reload dunst
if is_installed dunst; then
  pkill dunst
  dunst \
    -lb "${color0:=#F0F0F0}" \
    -nb "$color0" \
    -cb "$color0" \
    -lf "${color8:=#000000}" \
    -bf "$color8" \
    -cf "$color8" \
    -nf "$color8" \
    > /dev/null 2>&1 &
fi

# Reload gcalert
if is_installed gcalert; then
  pkill gcalert
  gcalert &
fi

# Start or reload polybar
if !is_installed wal && pgrep 'polybar' > /dev/null; then
  pkill -USR1 polybar
elif is_installed polybar; then
  polybar default &
fi
