#!/bin/sh

# String of colors 31 to 36, separated by newlines
colors=''
for i in $(seq 1 6); do
  colors=$(printf '%s\n3%s' "$colors" "$i")
done

# Multiline string of the graphic to display
graphic="
    ▄████▄⠀
   ███▀████
▄▄████▄████
  ▀████████
    ███████"

# Displays each line of $1 using the colors on each line of $2
display_graphic() {
  IFS=$(printf '\n\r')
  for line in $1; do
    for color in $2; do
      printf ' \e[%sm%s ' "${color}" "${line}"
    done

    printf '\n'
  done
}

# Display the normal colors
display_graphic "$graphic" "$colors"

# Display the bold colors
printf '\e[1m\n'
display_graphic "$graphic" "$colors"

# Reset all colors
printf '\e[0m\n'
