#!/usr/bin/env bash
# Runs whizkers with environment variable support, asks for a theme using
# dmenu, and reloads the desktop.

#yes 2>/dev/null | relink-config >/dev/null

#if [ "$?" -ne 0 ]; then
  #echo 'relink-config FAILED'
  #exit 1
#fi

if [ "$#" -eq 0 ]; then
  selected=$(whizkers -l |\
    dmenu -i -f -b -sb "#3f91c0" -p 'Whizkers')
  [ -z "$selected" ] && exit 0
  whizkers -e $selected >/dev/null
else
  whizkers -e "$@" >/dev/null
fi

[ "$?" -ne 0 ] && exit 1

reload-desktop

exit 0
