#!/usr/bin/env bash
# Sets and reloads the theme using zenbu via argument or dmenu.
#
# Author:  Kate Hart (https://github.com/codehearts)
# Depends: dmenu, reload-desktop (custom), zenbu (pypi)

if [ "$#" -eq 0 ]; then
  selected=$(ls ~/Pictures/wallpaper/ |\
    dmenu -i -f -b -sb '#000000' -p 'Zenbu')
  [ -z "$selected" ] && exit 0
  zenbu && wal -i ~/Pictures/wallpaper/$selected >/dev/null
else
  zenbu "$@" >/dev/null
fi

[ "$?" -ne 0 ] && exit 1

reload-desktop

exit 0
